### ISSUE TITLE
upstreaming the applet

### ISSUE THREAD

**Issue by fossfreedom** [danielpinto8zz6/budgie-network-applet#2]
Good work with this effort!

I know Ikey started producing a network applet but did not finish :(

Is it your intention to upstream this to the solus-project ...  basically to do what Ikey did not finish?

Looks like the Licenses for this project and budgie-desktop are compatible so that should be ok.

**Comment by danielpinto8zz6** [comment]
Hi, 
yeah at that time me and ikey had talked about an implementation of the network applet, but he did not wanted a fork because of the dependencies, however i managed to remove all the unnecessary dependencies.
If the solus team is interested in adding as an upstream, I'll be happy to continue supporting the applet.

**Comment by fossfreedom** [comment]
If Josh is not aware already maybe raise an issue on the solus tracker making the offer to create a PR for this applet?

**Comment by danielpinto8zz6** [comment]
https://github.com/solus-project/budgie-desktop/issues/1623

**Comment by danielpinto8zz6** [comment]
@fossfreedom  https://www.youtube.com/watch?v=wjuamlW6Zxw 4:01:42
I guess not

**Comment by fossfreedom** [comment]
Odd that no discussion via the issue you raised.  Suggest wait until formal confirmation - maybe Bryan can add further thoughts on the design that was briefly described.

I'll close this here since it is being tracked upstream.
